

---
- hosts: all
  become: true
  tasks:
    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
      register: output


    - debug:
       var: output  
