---
- name: Understanding vars
  hosts: all
  gather_facts: False
  become: yes
    #vars:
    #USRNM: playuser
    #COMM: Variable from playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: output

    - name: Output
      debug:
        var: output.comment


    - debug: 
       var: output.name
